EQUIPOS = {
    "Atlas": "atlas",
    "Atlético de San Luis": "atletico_de_san_luis",
    "Guadalajara": "cd_guadalajara",
    "América": "club_america",
    "León": "club_leon",
    "Tijuana": "club_tijuana",
    "Cruz Azul": "cruz_azul",
    "Juárez": "fc_juarez",
    "Mazatlán": "mazatlan_fc",
    "Monterrey": "monterrey",
    "Necaxa": "necaxa",
    "Pachuca": "pachuca",
    "Puebla": "puebla",
    "Querétaro": "queretaro_fc",
    "Santos Laguna": "santos_laguna",
    "Tigres UANL": "tigres_uanl",
    "Toluca": "toluca",
    "Pumas UNAM": "unam_pumas",
}
